config/routes.rb
Rails.application.routes.draw do
  resources :users
  
  devise_for :users
  root to: 'pages#home'

  
  resources :students
  resources :lectures
  resources :classrooms
  resources :semesters
  resources :courses
  resources :subjects
  resources :teachers
  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :teacher
  belongs_to :semester
  belongs_to :subject
  has_many :lectures
  
  has_many :classroom_students
  has_many :students, through: :classroom_students
end

app/models/classroom_student.rb
class ClassroomStudent < ApplicationRecord
  belongs_to :classroom
  belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :department
  has_many :subject_courses
  has_many :students, through: :subject_courses
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :courses
    has_many :teachers
    has_many :subjects
end

app/models/equivalence.rb
class Equivalence < ApplicationRecord
  belongs_to :subject
  belongs_to :discipline, class_name: 'Subject'
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :classroom
  has_many :lecture_students
  has_many :students, through: :lecture_students
end

app/models/lecture_student.rb
class LectureStudent < ApplicationRecord
  belongs_to :lecture
  belongs_to :student
end

app/models/semester.rb
class Semester < ApplicationRecord
    has_many :classrooms
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course
  has_many :lecture_students
  has_many :lectures, through: :lecture_students

  has_many :classroom_students
  has_many :classrooms, thourgh: :classroom_students
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :department, optional: true

  has_many :equivalences
  has_many :equivalent_disciplines, through: :equivalences, source: :discipline

  has_many :subject_courses
  has_many :courses, through: :subject_courses
end

app/models/subject_course.rb
class SubjectCourse < ApplicationRecord
  belongs_to :subject
  belongs_to :course
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :department
  has_many :classrooms
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_one :teahcer

    mount_uploader :photo, PhotoUploader
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name, :register, :course_id)
    end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :register %>
    <%= form.text_field :register %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.text_field :course_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Register</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.register %></td>
        <td><%= student.course %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Register:</strong>
  <%= @student.register %>
</p>

<p>
  <strong>Course:</strong>
  <%= @student.course %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>