config/routes.rb
Rails.application.routes.draw do
  resources :users
  
  devise_for :users
  root to: 'pages#home'

  
  resources :students
  resources :lectures
  resources :classrooms
  resources :semesters
  resources :courses
  resources :subjects
  resources :teachers
  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :teacher
  belongs_to :semester
  belongs_to :subject
  has_many :lectures
  
  has_many :classroom_students
  has_many :students, through: :classroom_students
end

app/models/classroom_student.rb
class ClassroomStudent < ApplicationRecord
  belongs_to :classroom
  belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :department
  has_many :subject_courses
  has_many :students, through: :subject_courses
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :courses
    has_many :teachers
    has_many :subjects
end

app/models/equivalence.rb
class Equivalence < ApplicationRecord
  belongs_to :subject
  belongs_to :discipline, class_name: 'Subject'
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :classroom
  has_many :lecture_students
  has_many :students, through: :lecture_students
end

app/models/lecture_student.rb
class LectureStudent < ApplicationRecord
  belongs_to :lecture
  belongs_to :student
end

app/models/semester.rb
class Semester < ApplicationRecord
    has_many :classrooms
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course
  has_many :lecture_students
  has_many :lectures, through: :lecture_students

  has_many :classroom_students
  has_many :classrooms, thourgh: :classroom_students
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :department, optional: true

  has_many :equivalences
  has_many :equivalent_disciplines, through: :equivalences, source: :discipline

  has_many :subject_courses
  has_many :courses, through: :subject_courses
end

app/models/subject_course.rb
class SubjectCourse < ApplicationRecord
  belongs_to :subject
  belongs_to :course
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :department
  has_many :classrooms
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_one :teahcer

    mount_uploader :photo, PhotoUploader
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:department_id, :name)
    end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :department_id %>
    <%= form.text_field :department_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Subjects</h1>

<table>
  <thead>
    <tr>
      <th>Department</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subjects.each do |subject| %>
      <tr>
        <td><%= subject.department %></td>
        <td><%= subject.name %></td>
        <td><%= link_to 'Show', subject %></td>
        <td><%= link_to 'Edit', edit_subject_path(subject) %></td>
        <td><%= link_to 'Destroy', subject, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subject', new_subject_path %>

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Department:</strong>
  <%= @subject.department %>
</p>

<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>