config/routes.rb
Rails.application.routes.draw do
  resources :users
  
  devise_for :users
  root to: 'pages#home'

  
  resources :students
  resources :lectures
  resources :classrooms
  resources :semesters
  resources :courses
  resources :subjects
  resources :teachers
  resources :departments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :teacher
  belongs_to :semester
  belongs_to :subject
  has_many :lectures
  
  has_many :classroom_students
  has_many :students, through: :classroom_students
end

app/models/classroom_student.rb
class ClassroomStudent < ApplicationRecord
  belongs_to :classroom
  belongs_to :student
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :department
  has_many :subject_courses
  has_many :students, through: :subject_courses
end

app/models/department.rb
class Department < ApplicationRecord
    has_many :courses
    has_many :teachers
    has_many :subjects
end

app/models/equivalence.rb
class Equivalence < ApplicationRecord
  belongs_to :subject
  belongs_to :discipline, class_name: 'Subject'
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :classroom
  has_many :lecture_students
  has_many :students, through: :lecture_students
end

app/models/lecture_student.rb
class LectureStudent < ApplicationRecord
  belongs_to :lecture
  belongs_to :student
end

app/models/semester.rb
class Semester < ApplicationRecord
    has_many :classrooms
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :course
  has_many :lecture_students
  has_many :lectures, through: :lecture_students

  has_many :classroom_students
  has_many :classrooms, thourgh: :classroom_students
end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :department, optional: true

  has_many :equivalences
  has_many :equivalent_disciplines, through: :equivalences, source: :discipline

  has_many :subject_courses
  has_many :courses, through: :subject_courses
end

app/models/subject_course.rb
class SubjectCourse < ApplicationRecord
  belongs_to :subject
  belongs_to :course
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :department
  has_many :classrooms
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_one :teahcer

    mount_uploader :photo, PhotoUploader
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :department_id)
    end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :department_id %>
    <%= form.text_field :department_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.department %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Department:</strong>
  <%= @teacher.department %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>